# Generated by Django 4.1.1 on 2022-11-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
