# Generated by Django 4.1.1 on 2022-11-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='static\\images'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
