# Generated by Django 4.1.1 on 2022-12-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_img1_alter_contact_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='res1',
            field=models.CharField(default='na', max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='res2',
            field=models.CharField(default=('na', 'na'), max_length=22),
            preserve_default=False,
        ),
    ]
