# Generated by Django 4.1.1 on 2022-12-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_res1_contact_res2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
